### ISSUE TITLE
Create an object to make the needed server calls

### ISSUE THREAD

**Issue by SeanMarcoux** [SOEN341/Schedule-Builder#11]
So that the front end team can start coding the behavior of the UI, there should be some fake server calls in place (have it return hard coded values instead of running the actual algorithms). We will later replace these with the real server behavior when that code is complete.

**Comment by SeanMarcoux** [comment]
I'm changing this issue. We need 2 objects for this:

1) A mocked server bridge, which will simply return the expected values when the appropriate functions are called. (ie serverBridge.getCourses() will return a hard coded array of courses) This will allow us to work on the UI without needing the proper server functionality to be implemented yet.

2) The real server bridge. This will perform the proper AJAX server requests in each of its functions. (ie serverBridge.getCourses() will actually request the courses from the server, which will pull them out of the database) This will be the final implementation that we will use once the backend has finished all of its programming

**Comment by Cavonte** [comment]
For 1) do you mean the courses of the user. Or the more generic list of course that the admin can modify.
For 2) I have identified these for the server calls. Are they correct ?
-change email 
-password
-username
-add class taken
-add classes needed

**Comment by SeanMarcoux** [comment]
1) That was just an example, but that would be for the full list of courses. We have a few uses for that on the front-end, one of them being for the admin as you said.
2) I think we'll need a lot more than that. We'll discuss this at the meeting tomorrow

**Comment by SeanMarcoux** [comment]
Most of the server calls are in place. We just need to confirm what form Section objects will be and what the data returned from a generated schedule will look like and then this task can be finalized

**Comment by Cavonte** [comment]
can we close this too ?

**Comment by SeanMarcoux** [comment]
No. Until I have the admin page, I can't test all the server calls on our end, so I can't confirm that they're working as intended. I will close them as soon as I test this

**Comment by SeanMarcoux** [comment]
Server calls have all been tested and work on the front-end save for some minor issues
