### ISSUE TITLE
Figure out the teams

### ISSUE THREAD

**Issue by SeanMarcoux** [SOEN341/Schedule-Builder#2]
We need to figure out what needs to be done and split into appropriate teams

**Comment by SeanMarcoux** [comment]
We initially created a front-end and back-end team, but this will be changed since documentation is a much larger component than we initially thought

**Comment by Lessi14** [comment]
The team has been divided into 3 parts: 3 front-end programmers, 3 back-end programmers, and 6 people on documentation.
