### ISSUE TITLE
Create Admin Page

### ISSUE THREAD

**Issue by SeanMarcoux** [SOEN341/Schedule-Builder#25]
We need a page for the admin to land on. Here he will be able to do all of his admin activities:
1) Add/remove/edit courses
2) Add/remove/edit sections

I'm thinking the page will be a list of courses, with buttons next to them to edit or remove and an "Add course" button on the bottom. Editing/adding will both pop up dialog. For section management, that could maybe be done from the edit course dialog, but if you have a better idea, go ahead. Maybe this could be done from a separate page

**Comment by SeanMarcoux** [comment]
Think about adding a search bar to this, so they can search for specific courses. It could work like google

**Comment by adrielFab** [comment]
i can take care

**Comment by adrielFab** [comment]
Ill take care

**Comment by SeanMarcoux** [comment]
I've been thinking about this and I'm pretty sure the best way is to have the page with the list of courses like I originally said (with add and delete functionality), but then a user can click into a course if they want to edit it. This would bring them to a page for this course along with a list of sections for this course.
This would call for a page that can be generalized for all courses. Figuring out which course you want to load for that page can be handled with cookies by just setting the course code or something similar in a cookie and then loading that when the page opens and making the proper server calls to obtain all the data for that course

**Comment by GabrieleBavaro** [comment]
So I have the main admin page done with the button, just creating the part where when u want to edit a course it brings you to a page with that course's info to edit.

**Comment by SeanMarcoux** [comment]
I'm taking over this issue to ensure it is done ASAP and Gabriel will move on to some other tasks

**Comment by SeanMarcoux** [comment]
I have finished with the admin courses page and am now working on the sections page

**Comment by SeanMarcoux** [comment]
Course editing has been implemented. Now I just need to add section management (adding, removing, and editing)

**Comment by SeanMarcoux** [comment]
The pages have been completed now
