### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by Cavonte** [SOEN341/Schedule-Builder#28]
So how is persistent data going to be handled ? This might be necessary to restrain access to certain pages but also identify the current user when the time comes to make server calls.

**Comment by SeanMarcoux** [comment]
Other than the user's username, what else do we need persistence on? We can easily store the data in a cookie. Javascript can manage cookies

**Comment by SeanMarcoux** [comment]
Persistence is now handled through the cookieManager object. I have implemented it in all of our existing pages so far and will use it when building other pages
