### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by adrielFab** [SOEN341/Schedule-Builder#32]

**Comment by SeanMarcoux** [comment]
Adriel updated the log in page.
I updated the main admin page. The other admin page looks fine in my opinion

**Comment by SeanMarcoux** [comment]
@adrielFab If you could update the look of the Account Information page, that would be awesome. That is the one page that I still think looks shitty. The only other thing I'd say is maybe look at changing the colors on the preferences page

**Comment by adrielFab** [comment]
Cool cool
