### ISSUE TITLE
Implement Server Calls on the Back-End

### ISSUE THREAD

**Issue by SeanMarcoux** [SOEN341/Schedule-Builder#35]
The server calls need to be handled on the back-end and behave as expected

**Comment by Cavonte** [comment]
On it already. As a side note, I cant get the app to work, so I am working with backend only for now.

**Comment by SeanMarcoux** [comment]
Is this done? If I'm correct all we have left is the forgot password server call and the scheduling algorithm calls? If so, you should close this issue since I made separate tasks for those more complicated server calls

**Comment by Cavonte** [comment]
yes they are done and mostly tested. I will close the issue.
